'use strict';
const $ = id => document.getElementById(id);
const token = document.querySelector('meta[name="review-token"]').content;
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = value => value == null ? 'Undetermined' : Number(value).toLocaleString('en-US', {maximumFractionDigits:2});
const money = value => value == null ? 'Undetermined' : `CNY ${number(value)}`;
let state, selected, screen = 'input', documentTab = 'contract', toastTimer;
const drafts = new Map();
const short = label => ({'No cut-off exception identified':'No exception','Premature recognition':'Premature recognition','Delayed or omitted recognition':'Delayed / omitted','Additional evidence required':'Evidence required','Outside prototype scope — human review required':'Outside scope'}[label] || 'Not run');
const category = label => label === state?.labels[3] || label === state?.labels[4] ? 'evidence' : [state?.labels[1],state?.labels[2]].includes(label) ? 'exception' : '';
const item = () => state.items.find(i => i.id === selected);
const reviewer = () => {const name = $('reviewer').value.trim(); if (!name) { $('reviewer').focus(); throw new Error('Enter your reviewer name in the top bar first.'); } return name;};

function toast(message, error=false) { clearTimeout(toastTimer); $('toast').textContent=message; $('toast').className=`toast${error?' error':''}`; $('toast').hidden=false; toastTimer=setTimeout(()=>$('toast').hidden=true,error?10000:4500); }
async function api(path, data) {
  const response=await fetch(path,{method:data===undefined?'GET':'POST',headers:{'X-Review-Token':token,...(data===undefined?{}:{'Content-Type':'application/json'})},...(data===undefined?{}:{body:JSON.stringify(data)})});
  if (!response.ok) {let error;try{error=(await response.json()).error;}catch{error='Unable to reach the local workspace.';}throw new Error(error);}
  return response;
}
async function mutate(path,data) {state=await (await api(path,data)).json();render();}
function status(i) {return ({unrun:'AI not run',ready:'Awaiting review',needs_rerun:'Rerun required',running:'AI running',queued:'Queued',failed:'Run failed',reviewed:'Review complete'})[i.status];}
function badge(i){return `<span class="pill ${i.review?'reviewed':category(i.result?.conclusion)}">${esc(i.review?'Human reviewed':short(i.result?.conclusion))}</span>`;}
function fact(label,value){return `<div class="fact"><small>${esc(label)}</small><strong>${esc(value ?? 'Not supplied')}</strong></div>`;}
function preserveDrafts(){
  for(const id of ['evidence-form','review-form']){const form=$(id);if(form&&selected){const values={};for(const element of form.elements){if(element.name)values[element.name]=element.type==='checkbox'?element.checked:element.value;}drafts.set(`${selected}:${id}`,values);}}
}
function restoreDrafts(){
  for(const id of ['evidence-form','review-form']){const form=$(id),values=drafts.get(`${selected}:${id}`);if(form&&values){for(const [name,value] of Object.entries(values)){const input=form.elements.namedItem(name);if(input){if(input.type==='checkbox')input.checked=value;else input.value=value;}}}}
}
function filtered(){const search=$('search').value.toLowerCase(),filter=$('filter').value;return state.items.filter(i=>{
  if(!`${i.id} ${i.case.contract.customer}`.toLowerCase().includes(search))return false;
  if(filter==='attention')return category(i.result?.conclusion)!=='';
  if(filter==='evidence')return category(i.result?.conclusion)==='evidence';
  if(filter==='pending')return !i.review;
  if(filter==='reviewed')return !!i.review;
  return true;
});}
function renderQueue(){const rows=filtered();$('queue-total').textContent=rows.length;$('queue').innerHTML=rows.map(i=>`<button class="queue-item ${selected===i.id?'active':''}" data-case="${esc(i.id)}" aria-current="${selected===i.id?'true':'false'}"><div class="row"><strong>${esc(i.id)}</strong><span class="dot ${i.review?'reviewed':category(i.result?.conclusion)}"></span></div><small>${esc(i.case.contract.customer)}</small><div class="queue-label">${esc(i.review?'Reviewed · '+short(i.review.conclusion):short(i.result?.conclusion))}</div></button>`).join('')||'<p class="empty">No matching transactions.</p>';}
function choose(id){preserveDrafts();selected=id;screen='workbench';documentTab='contract';render();}
function render(){
  if(!state)return;if(!state.items.some(i=>i.id===selected))selected=state.items[0]?.id;
  $('workbench-overview').hidden=screen!=='workbench';
  $('clear-filters').disabled=state.busy;
  const reviewed=state.items.filter(i=>i.review).length,exceptions=state.items.filter(i=>category(i.result?.conclusion)==='exception').length,evidence=state.items.filter(i=>category(i.result?.conclusion)==='evidence').length;
  $('stats').innerHTML=[['Transactions',state.items.length,'One batch per transaction','▤'],['AI exceptions',exceptions,'Draft findings to verify','↗'],['AI evidence requests',evidence,'Based on the latest AI result','◷'],['Human reviewed',`${reviewed} / ${state.items.length}`,'Explicit auditor decisions','✓']].map(([label,value,sub,icon])=>`<div class="stat"><span class="stat-label">${label}</span><span class="stat-icon">${icon}</span><strong>${value}</strong><p>${sub}</p></div>`).join('');
  $('review-count').textContent=reviewed;
  $('source-info').textContent=state.source_run?'Saved AI results loaded · changes saved locally':'New workspace · no AI results yet';
  const pending=state.items.filter(i=>['unrun','needs_rerun','failed'].includes(i.status)&&i.source_check);
  $('run-pending').disabled=state.busy||!pending.length;
  $('run-pending').textContent=state.busy?'AI checks in progress…':`Run pending AI checks${pending.length?` (${pending.length})`:''}`;
  $('run-banner').hidden=!state.busy;
  $('run-banner').textContent=`AI is reviewing ${state.items.find(i=>i.status==='running')?.id || 'the next transaction'} · ${state.items.filter(i=>['queued','running'].includes(i.status)).length} remaining. You can keep browsing. Do not close the local Python server.`;
  $('input-nav').classList.toggle('active',screen==='input');$('input-page').hidden=screen!=='input';
  $('workbench-nav').classList.toggle('active',screen==='workbench');$('summary-nav').classList.toggle('active',screen==='summary');
  $('workbench').hidden=screen!=='workbench';$('summary').hidden=screen!=='summary';renderQueue();
  if(screen==='workbench')renderWorkbench();else if(screen==='summary')renderSummary();else renderInput();
}
function documentContent(i){
  const c=i.case,doc=c[documentTab];let content='';
  if(documentTab==='contract')content=`<div class="facts">${fact('Customer',doc.customer)}${fact('Goods',doc.goods)}${fact('Contract quantity',number(doc.quantity)+' units')}${fact('Unit price',money(doc.unit_price_cny))}${fact('Contract value',money(doc.total_price_cny))}${fact('Basis','Credit sale · excluding tax')}</div><div class="contract-quote">${esc(doc.terms)}</div>`;
  if(documentTab==='ledger')content=`<div class="facts">${fact('Accounting date',doc.accounting_date)}${fact('Accounting period',doc.accounting_period)}${fact('Debit account',doc.entry.debit_account)}${fact('Debit amount',money(doc.entry.debit_cny))}${fact('Credit account',doc.entry.credit_account)}${fact('Credit amount',money(doc.entry.credit_cny))}</div><p class="muted narrative">Use the ledger date to determine the recorded period. Invoice issuance alone is not a ledger entry.</p>`;
  if(documentTab==='invoice')content=`<div class="facts">${fact('Invoice date',doc.invoice_date)}${fact('Invoice quantity',number(doc.quantity)+' units')}${fact('Invoice amount',money(doc.amount_cny))}${fact('Transaction',doc.transaction_id)}</div><p class="muted narrative">Match the invoice to the contract, ledger and delivery evidence.</p>`;
  if(documentTab==='delivery')content=`<div class="facts">${fact('Batch',doc.batch_id)}${fact('Evidence revision',i.evidence_version)}${fact('Actual dispatch / collection',doc.actual_dispatch_date)}${fact('Dispatched quantity',doc.dispatched_quantity == null ? 'Not supplied':number(doc.dispatched_quantity))}${fact('Actual customer receipt',doc.actual_customer_receipt_date)}${fact('Received quantity',doc.received_quantity == null ? 'Not supplied':number(doc.received_quantity))}${fact('Actual substantive acceptance',doc.actual_customer_acceptance_date)}${fact('Accepted quantity',doc.accepted_quantity == null ? 'Not supplied':number(doc.accepted_quantity))}</div><p class="muted narrative">${esc(doc.note)}</p>`;
  return `<div class="document-id"><span class="doc-dot"></span>${esc(doc.document_id)}<span>· Structured source record</span></div>${content}`;
}
function renderWorkbench(){
  const i=item();if(!i){$('workbench').innerHTML='<div class="card card-body"><h2>No source evidence loaded</h2><p class="muted narrative">Open Source input to import your JSON package and start a new review.</p></div>';return;}const c=i.case,r=i.result,kind=category(r?.conclusion),locked=state.busy,canReview=['ready','reviewed'].includes(i.status)&&r&&i.source_check;
  const fields=[['actual_dispatch_date','Actual dispatch / customer collection'],['actual_customer_receipt_date','Customer receipt'],['actual_customer_acceptance_date','Substantive customer acceptance']];
  const result=r?`<div class="ai-conclusion ${kind}"><small>AI conclusion · subject to human review</small><h3>${esc(r.conclusion)}</h3><div class="amount">Cut-off difference <strong>${money(r.difference_cny)}</strong></div></div><div class="facts">${fact('Qualifying event date',r.qualifying_event_date||'Unknown — evidence needed')}${fact('Recorded accounting date',r.recorded_accounting_date)}${fact('Eligible quantity in 2025',number(r.eligible_quantity_by_cutoff))}${fact('Recorded quantity in 2025',number(r.recorded_quantity_in_2025))}</div><div class="narrative"><div class="section-label">Recognition condition</div><p>${esc(r.recognition_condition)}</p></div><div class="narrative"><div class="section-label">AI explanation</div><p>${esc(r.explanation)}</p></div><div class="refs">${r.evidence_references.map(ref=>`<span class="ref">${esc(ref)}</span>`).join('')}</div>${r.additional_evidence_requested.length?`<div class="narrative"><div class="section-label">Requested evidence</div><ul class="request-list">${r.additional_evidence_requested.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}`:`<p class="empty">${i.status==='running'?'Reviewing the supplied evidence…':'Confirm source records in step 01 to start AI assessment automatically.'}</p>`;
  $('workbench').innerHTML=`<div class="case-head"><div><h2>${esc(i.id)} <span>/</span> ${esc(c.contract.customer)}</h2><p>${esc(c.contract.goods)} · ${number(c.contract.quantity)} units · ${money(c.contract.total_price_cny)}</p></div><span class="pill ${i.review?'reviewed':''}">${status(i)}</span></div>
  <div class="columns"><div class="column">
    <article class="card"><div class="card-head"><h3><span class="card-number">01</span> Source records & human check</h3><small>4 linked records · no AI extraction</small></div><div class="doc-tabs" role="tablist">${['contract','ledger','invoice','delivery'].map(t=>`<button class="doc-tab ${documentTab===t?'active':''}" role="tab" aria-selected="${documentTab===t}" data-doc="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><div class="card-body" id="document-content">${documentContent(i)}</div><div class="card-body source-check">${i.source_check?`<div class="review-stamp">✓ Source records verified by ${esc(i.source_check.reviewer)} · evidence revision ${i.source_check.evidence_version}</div>`:''}<p class="evidence-intro">These fields are parsed from your structured input. Check all four records against the supporting evidence before AI analysis.</p><form id="source-form"><label class="check"><input type="checkbox" name="confirmed" required><span>I checked the contract, ledger, invoice and delivery fields. They faithfully represent the supplied evidence, including any missing information.</span></label><button class="button primary" ${locked?'disabled':''}>Confirm source records & run AI ↗</button></form></div></article>
    <article class="card"><div class="card-head"><h3><span class="card-number">03</span> Supplement evidence</h3><small>Auditor checkpoint</small></div><div class="card-body"><p class="evidence-intro">Check the supporting record, then enter the verified event below. Saving creates a new evidence revision and reruns this transaction through AI.</p>
    <form id="evidence-form"><div class="form-grid"><label class="wide">Event to supplement<select name="field" required><option value="">Select the event to verify</option>${fields.map(([key,name])=>`<option value="${key}">${name}</option>`).join('')}</select></label><label>Verified event date<input name="date" type="date" required max="${esc(state.context.records_available_through)}"></label><label>Full batch quantity<input name="quantity" type="number" min="1" step="1" value="${c.contract.quantity}" required></label><label class="wide">Supporting document reference<input name="source_reference" required placeholder="e.g. Signed receipt SR-009" maxlength="200"></label><label class="wide">What does the evidence establish?<textarea name="note" rows="2" required maxlength="3000" placeholder="Describe the evidence checked and how it resolves the request."></textarea></label></div><label class="check"><input type="checkbox" name="confirmed" required><span>I have checked the supporting evidence. This is a verified fact, not an assumption.</span></label><div class="form-actions"><small>One paid OpenRouter call.<br>Previous evidence and decisions stay in history.</small><button class="button primary" type="submit" ${locked||!i.source_check?'disabled':''}>Confirm evidence & rerun ↗</button></div></form>
    <details class="history"><summary>Evidence history (${i.evidence.length})</summary>${i.evidence.map(e=>`<div class="history-item"><strong>Revision ${e.evidence_version} · ${esc(e.source_reference)}</strong><p>${esc(e.field)}: ${esc(e.previous_date||'Unknown')} → ${esc(e.date)} · ${e.quantity} units</p><p>${esc(e.note)}</p><small>${esc(e.reviewer)} · ${esc(e.at)}</small></div>`).join('')||'<p class="muted narrative">No supplemental evidence recorded.</p>'}</details></div></article>
  </div><div class="column">
    <article class="card"><div class="card-head"><h3><span class="card-number">02</span> AI assessment</h3><small>${i.attempts.at(-1)?.kind==='saved evaluation'?'Saved test result':'Review session result'}</small></div><div class="card-body">${i.error?`<div class="note error">${esc(i.error)}</div>`:''}${['needs_rerun','running','queued'].includes(i.status)&&r?'<div class="note amber">Previous result shown for reference. Review is locked until the latest check completes.</div>':''}${result}<div class="ai-foot"><span>GPT-4.1 mini · via OpenRouter</span></div><p class="muted">Analysis starts after source or supplemental evidence confirmation.</p><details class="history"><summary>AI result history (${i.attempts.length})</summary>${i.attempts.slice().reverse().map(a=>`<div class="history-item"><strong>${esc(a.kind)} · evidence revision ${a.evidence_version}</strong><p>${esc(a.result?.conclusion||a.error||'No result')}</p><small>${esc(a.at)} · ${a.reported_cost_usd==null?'Cost unknown':`USD ${Number(a.reported_cost_usd).toFixed(6)}`}</small><details><summary>View preserved output</summary><pre>${esc(JSON.stringify(a.result||{error:a.error},null,2))}</pre></details></div>`).join('')||'<p class="muted narrative">No AI attempts yet.</p>'}</details></div></article>
    <article class="card"><div class="card-head"><h3><span class="card-number">04</span> Human review</h3><small>Required for every transaction</small></div><div class="card-body">${i.review?`<div class="review-stamp"><strong>✓ ${i.review.decision==='overridden'?'AI finding revised':'AI finding confirmed'} by ${esc(i.review.reviewer)}</strong><p>${esc(i.review.conclusion)} · ${money(i.review.difference_cny)}</p><p>${esc(i.review.note)}</p><small>${esc(i.review.at)}</small></div>`:'<p class="evidence-intro">Compare the conclusion and amount with the source records. Confirm the AI finding or record your own supported conclusion.</p>'}${category(r?.conclusion)==='evidence'?'<div class="note amber">Resolve the evidence request before closing this transaction. If the request is unnecessary, explain your evidence-based override below.</div>':''}<form id="review-form"><div class="form-grid"><label class="wide">Final auditor conclusion<select name="conclusion" required><option value="">Select your conclusion</option>${state.labels.slice(0,3).map(label=>`<option value="${esc(label)}" ${(i.review?.conclusion||r?.conclusion)===label?'selected':''}>${esc(label)}</option>`).join('')}</select></label><label class="wide">Final cut-off difference (CNY)<input type="number" name="difference_cny" min="0" step="0.01" required value="${esc(i.review?.difference_cny??r?.difference_cny??'')}" placeholder="0 when no exception"></label><label class="wide">Review rationale<textarea name="note" rows="2" required maxlength="3000" placeholder="Reference the evidence supporting your final decision.">${esc(i.review?.note||'')}</textarea></label></div><label class="check"><input name="confirmed" type="checkbox" required><span>I have checked the source evidence, the conclusion and the amount. I take responsibility for this review decision.</span></label><button type="submit" class="button primary full-width" ${!canReview||locked?'disabled':''}>${i.review?'Update human review':'Confirm human review'} ✓</button></form><details class="history"><summary>Previous human decisions (${i.review_history.length})</summary>${i.review_history.map(h=>`<div class="history-item"><strong>${esc(h.conclusion)} · ${money(h.difference_cny)}</strong><p>${esc(h.note)}</p><small>${esc(h.reviewer)} · ${esc(h.at)} · evidence revision ${h.evidence_version}</small></div>`).join('')||'<p class="muted narrative">No superseded decisions.</p>'}</details></div></article>
  </div></div>`;
  const flow=$('workbench').querySelector('.columns');
  const cards=[...flow.querySelectorAll('.card')].sort((a,b)=>Number(a.querySelector('.card-number').textContent)-Number(b.querySelector('.card-number').textContent));
  flow.replaceChildren(...cards);
  restoreDrafts();
  $('source-form')?.addEventListener('submit',async event=>{event.preventDefault();try{await mutate('/api/source-check',{id:i.id,version:i.version,reviewer:reviewer(),confirmed:true});drafts.delete(`${i.id}:review-form`);render();toast('Source records confirmed. AI assessment is running automatically.');}catch(error){toast(error.message,true);}});
  $('evidence-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form));try{const name=reviewer();await mutate('/api/evidence-run',{id:i.id,version:i.version,reviewer:name,field:values.field,date:values.date,quantity:Number(values.quantity),source_reference:values.source_reference,note:values.note,confirmed:values.confirmed==='on'});drafts.delete(`${i.id}:evidence-form`);drafts.delete(`${i.id}:review-form`);render();toast('Evidence saved. AI is checking the revised transaction.');}catch(error){toast(error.message,true);}});
  $('review-form').addEventListener('submit',async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));try{await mutate('/api/review',{id:i.id,version:i.version,reviewer:reviewer(),conclusion:values.conclusion,difference_cny:Number(values.difference_cny),note:values.note,confirmed:values.confirmed==='on'});drafts.delete(`${i.id}:review-form`);render();toast('Human review saved. The original AI output is preserved.');}catch(error){toast(error.message,true);}});
}
function renderSummary(){
  const rows=filtered(),reviewed=state.items.filter(i=>i.review).length,remaining=state.items.length-reviewed;
  $('summary').innerHTML=`<div class="summary-header"><div><h2>Human review summary</h2><p>AI findings and final auditor decisions remain side by side. Showing ${rows.length} of ${state.items.length} transactions.</p></div><div class="summary-actions"><button id="export-draft" class="button secondary">Export working CSV ↓</button><button id="export-final" class="button primary" ${state.acceptance?'':'disabled'}>Export accepted CSV ↓</button></div></div><div class="table-wrap"><table><thead><tr><th>Transaction</th><th>AI conclusion</th><th>AI difference</th><th>Auditor conclusion</th><th>Final difference</th><th>Reviewer / status</th></tr></thead><tbody>${rows.map(i=>`<tr><td><button class="text-button" data-case="${i.id}">${i.id} ↗</button></td><td><span class="pill ${category(i.result?.conclusion)}">${esc(short(i.result?.conclusion))}</span></td><td class="money">${i.result?number(i.result.difference_cny):'—'}</td><td>${i.review?`<span class="pill reviewed">${esc(short(i.review.conclusion))}</span>${i.review.decision==='overridden'?'<small> · revised</small>':''}`:'<small>Awaiting human decision</small>'}</td><td class="money">${i.review?number(i.review.difference_cny):'—'}</td><td>${esc(i.review?.reviewer||status(i))}</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">No matching transactions.</div>'}</div><div class="accept-panel"><div><h3>${state.acceptance?'✓ Batch accepted':'Final acceptance'}</h3><p>${state.acceptance?`Accepted by ${esc(state.acceptance.reviewer)} · ${esc(state.acceptance.at)}`:`${reviewed} of ${state.items.length} human reviews complete. ${!state.items.length?'Import source evidence to start a review.':remaining?`${remaining} transaction${remaining===1?'':'s'} still need a decision.`:'All transactions are ready for your final check.'}`}</p>${state.acceptance?`<p>${esc(state.acceptance.note)}</p>`:`<progress value="${reviewed}" max="${state.items.length||1}" aria-label="Human review completion"></progress>`}</div><button id="accept-batch" class="button primary" ${state.can_accept&&!state.busy&&!state.acceptance?'':'disabled'}>Accept complete batch ✓</button></div><p class="muted narrative">Amounts are in CNY. Acceptance records completion of this review task; identified exceptions may still require action in the audit. Reviewer names are self-declared in this local prototype.</p>`;
  $('export-draft').addEventListener('click',()=>exportCSV(false));$('export-final').addEventListener('click',()=>exportCSV(true));
  $('accept-batch').addEventListener('click',()=>{try{reviewer();$('accept-dialog').showModal();}catch(error){toast(error.message,true);}});
}
async function runItems(items){try{const name=reviewer();preserveDrafts();await mutate('/api/run',{ids:items.map(i=>i.id),versions:Object.fromEntries(items.map(i=>[i.id,i.version])),reviewer:name});for(const i of items)drafts.delete(`${i.id}:review-form`);render();toast(`${items.length} paid AI check${items.length===1?'':'s'} started. Previous results remain in history.`);}catch(error){toast(error.message,true);}}
async function exportCSV(final){try{const response=await api('/api/export',{final});const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`cutoff-review-${final?'accepted':'working'}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){toast(error.message,true);}}
document.addEventListener('click',event=>{const target=event.target.closest('[data-case],[data-doc]');if(target?.dataset.case)choose(target.dataset.case);if(target?.dataset.doc){preserveDrafts();documentTab=target.dataset.doc;renderWorkbench();}});
$('input-nav').addEventListener('click',()=>{preserveDrafts();screen='input';render();});
$('workbench-nav').addEventListener('click',()=>{preserveDrafts();screen='workbench';render();});
$('summary-nav').addEventListener('click',()=>{preserveDrafts();screen='summary';render();});
$('search').addEventListener('input',()=>{renderQueue();if(screen==='summary')renderSummary();});
$('filter').addEventListener('change',()=>{renderQueue();if(screen==='summary')renderSummary();});
$('clear-filters').addEventListener('click',async()=>{try{await mutate('/api/reset',{revision:state.revision});drafts.clear();selected=null;screen='input';$('search').value='';$('filter').value='all';$('workbench').innerHTML='';$('accept-dialog').close();render();toast('Demo workspace cleared. Import a JSON package to start again.');}catch(error){toast(error.message,true);}});
$('run-pending').addEventListener('click',()=>runItems(state.items.filter(i=>['unrun','needs_rerun','failed'].includes(i.status)&&i.source_check)));
$('reviewer').value=localStorage.getItem('cutoff-reviewer')||'';$('reviewer').addEventListener('input',()=>localStorage.setItem('cutoff-reviewer',$('reviewer').value));
$('cancel-accept').addEventListener('click',()=>$('accept-dialog').close());
$('accept-form').addEventListener('submit',async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));try{await mutate('/api/accept',{revision:state.revision,reviewer:reviewer(),note:values.note,confirmed:values.confirmed==='on'});$('accept-dialog').close();toast('Batch acceptance recorded. Your accepted summary is ready to export.');}catch(error){toast(error.message,true);}});
async function refresh(){try{const next=await(await api('/api/state')).json();if(!state||next.revision!==state.revision||next.busy!==state.busy||next.items.some((i,n)=>i.status!==state.items[n]?.status)){preserveDrafts();state=next;render();}}catch(error){toast(error.message,true);}}
refresh();setInterval(refresh,2500);

function renderInput(){
  $('input-page').innerHTML=`<article class="card"><div class="card-head"><h2>Source evidence input</h2><span class="pill">Before the workbench</span></div><div class="card-body"><p class="evidence-intro">Import a structured evidence package containing the contract, ledger, invoice and delivery records for each transaction. This prototype parses JSON fields locally; it does not extract text from PDF, Word or scanned documents.</p><div class="note">Current batch: ${state.items.length} transactions. Importing starts a new batch without AI predictions. The current workspace is archived locally, and original evaluation files remain unchanged.</div><div class="form-actions"><button id="download-template" class="button secondary">Download one-case JSON template ↓</button><button id="open-current" class="button secondary">Review current batch →</button></div><form id="import-form"><label class="upload-label">Evidence package (.json)<input id="evidence-file" type="file" accept=".json,application/json" required></label><p id="file-preview" class="muted">Use the template or an existing inputs.json file. Supported scope: FY2025, CNY, one full batch per transaction.</p><label class="check"><input name="confirmed" type="checkbox" required><span>Start a new review batch with this synthetic evidence package and archive the current workspace.</span></label><button class="button primary" ${state.busy?'disabled':''}>Import records & open workbench →</button></form><div class="note import-note">Next: inspect the parsed fields in 01 → confirm source records → AI runs automatically in 02. If AI requests evidence, verify and confirm the supplement in 03 to rerun 02. Finish with human review in 04.</div></div></article>`;
  $('open-current').onclick=()=>{screen='workbench';render();};
  $('download-template').onclick=async()=>{try{const response=await api('/api/template');const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download='source-evidence-template.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){toast(error.message,true);}};
  $('evidence-file').onchange=async()=>{try{const file=$('evidence-file').files[0];if(!file)return;if(file.size>1900000)throw new Error('Maximum file size is 1.9 MB.');const data=JSON.parse(await file.text());$('file-preview').textContent=`${file.name} · ${data.cases?.length||0} transactions · cut-off ${data.cutoff_date||'missing'}. No AI calls on import.`;}catch(error){$('file-preview').textContent='Could not read this package: '+error.message;}};
  $('import-form').onsubmit=async event=>{event.preventDefault();try{const name=reviewer(),file=$('evidence-file').files[0];if(!file||file.size>1900000)throw new Error('Choose a JSON package below 1.9 MB.');const dataset=JSON.parse(await file.text());await mutate('/api/import',{dataset,revision:state.revision,reviewer:name,confirmed:true});drafts.clear();selected=state.items[0].id;screen='workbench';$('search').value='';$('filter').value='all';render();toast('Imported locally. Check the source fields before running AI.');}catch(error){toast(error.message,true);}};
}
